version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
      - db # added db credentials
    environment:
      - SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employee_db
      - SPRING_DATASOURCE_USERNAME: user
      - SPRING_DATASOURCE_PASSWORD: password

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on: # added depends_on to grafana 
      - prometheus
    volumes: # added volume to grafana
      - grafana-storage:/var/lib/grafana

# added below db details
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql 

volumes:
  grafana-storage:
  db_data: