spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL} # Added env variable from docker compose file
    driver-class-name: com.mysql.cj.jdbc.Driver # Changed driver class name to mysql driver name
    username: ${SPRING_DATASOURCE_USERNAME} # Added env variable from docker compose file
    password: ${SPRING_DATASOURCE_PASSWORD} # Added env variable from docker compose file
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true      
